apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html-volume-claim-dynamic 
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 3Mi
  # storageClassName: standard