apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html-volume-claim-static
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 3Mi
  storageClassName: standard
  volumeName: static-pv